### PR TITLE
Initial iteration of community content taxonomies

### PR DESCRIPTION
**Pull request by hdoro**
This PR lays the ground for community taxonomies. Specific categorizations may be replaced before we hit V1, but the overall system - especially the `taxonomy.combination` type - won't change, so this is good for merging 😄 

Oh, and you'll notice that, right now, contribution types just have a single `tags` array of references to taxonomies. That is intentionally wrong - I just wanted to get a prototype up and running in the front-end while we figure the design of the community out ;)

### CODE REVIEW

**Review by kmelve — CHANGES_REQUESTED** [review]
Overall good stuff!

Some minor things: 

- [ ] I believe we default to using JS files and not JSX files in this codebase

- [ ] The custom path input is cool, but doesn't seem to support validation messages, which is useful in this case since it does a check for unique slugs

image

- [ ] Not to be a party pooper, but I wonder if we should remove emojis from description fields?

**Comment by hdoro** [comment]
image

**Comment by hdoro** [comment]
> The custom path input is cool, but doesn't seem to support validation messages, which is useful in this case since it does a check for unique slugs

I thought I fixed it yesterday by adding `markers` to the `FormField`. It's working locally here 🤔 

image

> Not to be a party pooper, but I wonder if we should remove emojis from description fields?

I guess this depends on our tone, I wrote everything based on my style, but I agree we should define how to go about it. I removed the emojis from the person schema for now, let me know if I should do the same for the others and feel free to edit descriptions as you see fit 😉 

(PS: I misclicked and accidentally closed this PR, I'm reopening it)

**Review by p10e — APPROVED** [review]
I can confirm the validation errors now show up correctly.

**Pull request merged**
